spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/FullParty"
    username: "root"
    password: "tkfkdgksmswodn"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: fullpartyspring@gmail.com
    password: vqrb ahdv kort osgy
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 360581808223-e0a27i9h3ga7s11nbbp0crup54c018hg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
            client-id: 5c4a6fa8ed2e2fd26e4aa1efa59df9d6
            client-secret: rqZZqgu7arL5NqoBP0NuL4utlPvigJ17
            client-name: kakao
            redirect-uri: https://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: kakao_account
            user-name-attribute: id

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 10
  refresh-token-expiration-minutes: 60

logging:
  level:
    org.springframework.security: DEBUG

custom:
  url: "https://localhost:8080"

server:
  ssl:
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit
