spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/FullParty"
    username: "root"
    password: "tkfkdgksmswodn"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

logging:
  level:
    org.springframework.security: DEBUG